pipeline {
    agent any

    environment {
        // Force Gradle to use the correct Linux path inside the container
        JAVA_HOME = "/opt/java/openjdk"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Abhishekbodapati551/smile-capstone.git'
            }
        }

        stage('Build') {
            steps {
                sh 'chmod +x gradlew'
                // Pass Java home and ignore local gradle.properties overrides
                sh './gradlew assembleDebug -Dorg.gradle.java.home=$JAVA_HOME'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'app/build/outputs/apk/debug/*.apk', fingerprint: true
        }
    }
}
